### ISSUE TITLE
bootstrap-nightshade & bootstrap-blackbox do not work with :root variables

### ISSUE THREAD

**Issue by vinorodrigues** [vinorodrigues/bootstrap-dark-5#35]
One cannot have:

```
html.dark :root {
  --bs-some-css-var: “some css value”;
}
```

As nesting on :root does not work.

**Comment by vinorodrigues** [comment]
I have tried to create a workaround for this issue by declaring additional `:root` vars.

For example, where BS declares:
```css
.text-primary {
  --bs-text-opacity: 1;
  color: rgba(var(--bs-primary-rgb), var(--bs-text-opacity)) !important;
}
```

The "dark variants use the `*-alt` variable, e.g. in `-nightshade`:
```css
html.dark .text-primary {
  color: rgba(var(--bs-primary-rgb-alt), var(--bs-text-opacity)) !important;
}
```
...and `-blackbox` has:
```css
[data-bs-color-scheme=dark] .text-primary {
  color: rgba(var(--bs-primary-rgb-alt), var(--bs-text-opacity)) !important;
}
```

This is different from the other variants, where **no** `*-alt` variables are used.
